# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  quantumContainerRegistry: quantumdocker.azurecr.io
  imageName: $(quantumContainerRegistry)/qmt_base

trigger:
- master

steps:
- task: Docker@1
  displayName: Login to QuantumDocker
  inputs:
    azureSubscriptionEndpoint: 'Station Q Santa Barbara compute cluster'
    azureContainerRegistry: $(quantumContainerRegistry)
    command: login
- script: |
    docker build . -t $(imageName):$(Build.BuildId) -t $(imageName):latest
  displayName: Build QMT Image
- script: docker run -v $(System.DefaultWorkingDirectory)/test_results:/test_results $(imageName) pytest /app/qmt/tests --verbose -n auto --capture=no  --junit-xml=/test_results/TEST.xml --cov=qmt --cov-report=xml:/test_results/coverage.xml --cov-report=html:/test_results/htmlcov
  displayName: Run QMT Tests
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/TEST.xml'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
- script: docker push $(imageName)
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  displayName: Push Image to ACR
