name: py27
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy=1.15.*
  - scipy=1.1.*
  - petsc=3.8.*
  - sympy=1.0
  - sphinx=1.8.*
  - pyside=1.2.*
  - pip:
    - matplotlib==3.0.*
    - pytest==4.0.*
    - mpi4py==3.0.*
    - shapely==1.6.*
    - future==0.17.*
    - h5py==2.8.*
    - holoviews==1.10.*
    - tqdm==4.28.*
    - fenics==2017.2.*
    - dask==1.0.*
    - dask-jobqueue==0.4.*
    - jupyter==1.0.*
