name: py36
channels:
  - conda-forge
dependencies:
  - adaptive=0.7.2=py36_1000
  - alabaster=0.7.12=py_0
  - apipkg=1.5=py_0
  - appnope=0.1.0=py36_1000
  - asn1crypto=0.24.0=py36_1003
  - astroid=2.1.0=py36_1000
  - atomicwrites=1.2.1=py_0
  - attrs=18.2.0=py_0
  - autopep8=1.4.3=py_0
  - babel=2.6.0=py_1
  - backcall=0.1.0=py_0
  - bcrypt=3.1.4=py36h470a237_0
  - blas=1.1=openblas
  - bokeh=1.0.4=py36_1000
  - boost=1.66.0=py36_1
  - boost-cpp=1.66.0=1
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - cffi=1.11.5=py36h342bebf_1001
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - cloudpickle=0.6.1=py_0
  - cmake=3.13.2=h1e01633_1000
  - coin3d=4.0.0=hf1beacf_3
  - cryptography=2.3.1=py36hdbc3d79_1000
  - curl=7.63.0=heae2a1f_1000
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h1de35cc_1001
  - dask=1.1.0=py_1
  - dask-core=1.1.0=py_0
  - dask-jobqueue=0.4.1=py_0
  - decorator=4.3.2=py_0
  - descartes=1.1.0=py36_0
  - dill=0.2.8.2=py36_1000
  - distributed=1.25.2=py36_1000
  - docrep=0.2.5=py_0
  - docutils=0.14=py36_1001
  - eigen=3.3.7=h04f5b5a_1000
  - entrypoints=0.3=py36_1000
  - execnet=1.5.0=py_0
  - expat=2.2.5=h0a44026_1002
  - fastcache=1.0.2=py36h1de35cc_1001
  - fenics=2017.2.0=np113py36_3
  - flake8=3.7.6=py36_0
  - freecad=0.18b0=py36h1ae927f_2
  - freeimage=3.17.0=0
  - freetype=2.8.1=hfa320df_1
  - future=0.17.1=py36_1000
  - geos=3.7.1=h0a44026_1000
  - h5py=2.8.0=py36h470a237_0
  - hdf4=4.2.13=hf3c6af0_1002
  - hdf5=1.10.1=2
  - heapdict=1.0.0=py36_1000
  - holoviews=1.11.2=py_0
  - hpc05=v1.30=py36_0
  - hypre=2.11.2=1
  - icu=58.2=h0a44026_1000
  - idna=2.8=py36_1000
  - imagesize=1.1.0=py_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py36h24bf2e0_1001
  - ipyparallel=6.2.3=py36_1000
  - ipython=7.1.1=py36h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - isort=4.3.4=py36_1000
  - jedi=0.13.2=py36_1000
  - jinja2=2.10=py_1
  - jpeg=9c=h1de35cc_1001
  - jsoncpp=1.8.1=h2d50403_1
  - jsonschema=3.0.0a3=py36_1000
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.4=py_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36h04f5b5a_1002
  - krb5=1.16.3=h24a3359_1000
  - kwant=1.3.3=py36_blas_openblashd3ea46f_1
  - lazy-object-proxy=1.3.1=py36h1de35cc_1000
  - libcurl=7.63.0=h76de61e_1000
  - libcxx=7.0.0=h2d50403_2
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h0a44026_1005
  - libgfortran=3.0.1=h93005f0_2
  - libgfortran-ng=3.0.1=h93005f0_2
  - libiconv=1.15=h1de35cc_1004
  - libnetcdf=4.5.0=3
  - libogg=1.3.2=h1de35cc_1001
  - libpng=1.6.34=ha92aebf_2
  - libsodium=1.0.16=h1de35cc_1001
  - libssh2=1.8.0=hf30b1f0_1003
  - libtheora=1.1.1=h470a237_1
  - libtiff=4.0.10=h79f4b77_1001
  - libuv=1.24.0=h1de35cc_1000
  - libvorbis=1.3.5=h1de35cc_1001
  - libxml2=2.9.8=hf14e9c8_1005
  - libxslt=1.1.32=h33a18ac_1002
  - llvm-meta=7.0.0=0
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=h0a44026_1001
  - markupsafe=1.1.0=py36h1de35cc_1000
  - matplotlib=2.2.2=py36_1
  - mccabe=0.6.1=py_1
  - metis=5.1.0=h0a44026_1003
  - mistune=0.8.4=py36h1de35cc_1000
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py36h6b9c3cc_4
  - more-itertools=4.3.0=py36_1000
  - mpi=1.0=mpich
  - mpi4py=3.0.0=py36h77202c6_1004
  - mpich=3.2.1=h12d9a10_1007
  - mpmath=1.1.0=py_0
  - msgpack-python=0.6.1=py36h04f5b5a_0
  - mumps=5.1.2=blas_openblash613969f_0
  - mumps-mpi=5.0.2=blas_openblas_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - netgen=6.2.1804=py36_0
  - notebook=5.7.4=py36_1000
  - numpy=1.13.3=py36_blas_openblas_201
  - numpy-stl=2.9.0=py36h917ab60_1000
  - occt=7.2.0=3
  - olefile=0.46=py_0
  - openblas=0.2.20=8
  - openssl=1.0.2p=h1de35cc_1002
  - packaging=19.0=py_0
  - pandas=0.24.0=py36h0a44026_0
  - pandoc=2.5=1
  - pandocfilters=1.4.2=py_1
  - param=1.8.2=py_0
  - paramiko=2.4.2=py36_1000
  - parmetis=4.0.3=hc4b10a8_1002
  - parso=0.3.2=py_0
  - partd=0.3.9=py_0
  - pcre=8.41=h0a44026_1003
  - petsc=3.8.4=blas_openblas_0
  - petsc4py=3.8.1=py36_1
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pillow=5.2.0=py36h2dc6135_1
  - pip=19.0.1=py36_0
  - pivy=0.6.5a0=py36h9e2f8fd_1000
  - pkg-config=0.29.2=h112b980_1004
  - pluggy=0.8.1=py_0
  - ply=3.11=py_1
  - prometheus_client=0.5.0=py_0
  - prompt_toolkit=2.0.7=py_0
  - psutil=5.4.8=py36h1de35cc_1000
  - pthread-stubs=0.4=h1de35cc_1001
  - ptscotch=6.0.4=2
  - ptyprocess=0.6.0=py36_1000
  - py=1.7.0=py_0
  - pyasn1=0.4.4=py_1
  - pycodestyle=2.5.0=py_0
  - pycparser=2.19=py_0
  - pyflakes=2.1.0=py_0
  - pygments=2.3.1=py_0
  - pylint=2.2.2=py36_1000
  - pynacl=1.3.0=py36h1de35cc_1000
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.3.1=py_0
  - pyqt=5.6.0=py36hc26a216_1008
  - pyrsistent=0.14.9=py36h1de35cc_1000
  - pyside2=5.6.0a1=py36h98637d4_1004
  - pysocks=1.6.8=py36_1002
  - pytest=4.1.1=py36_1000
  - pytest-cov=2.6.1=py_0
  - pytest-datadir=1.3.0=py_0
  - pytest-forked=1.0.1=py_0
  - pytest-xdist=1.26.1=py_0
  - python=3.6.5=1
  - python-dateutil=2.7.5=py_0
  - python-utils=2.3.0=py_1
  - pytz=2018.9=py_0
  - pyviz_comms=0.7.0=py_0
  - pyyaml=3.13=py36h1de35cc_1001
  - pyzmq=17.1.2=py36h111632d_1001
  - qt=5.6.2=h9e3eb04_4
  - qtconsole=4.4.3=py_0
  - readline=7.0=hcfe32e1_1001
  - requests=2.21.0=py36_1000
  - rhash=1.3.6=h1de35cc_1001
  - rope=0.10.7=py_1
  - scalapack=2.0.2=h3480a31_1003
  - scipy=1.1.0=py36_blas_openblash7943236_201
  - scotch=6.0.6=hde27766_1002
  - send2trash=1.5.0=py_0
  - setuptools=40.6.3=py36_0
  - shapely=1.6.4=py36h2bcc7ef_1002
  - sip=4.18.1=py36h0a44026_1000
  - six=1.12.0=py36_1000
  - slepc=3.8.3=blas_openblas_0
  - slepc4py=3.8.0=py36_0
  - smesh=8.3.0b0=py36_7
  - snowballstemmer=1.2.1=py_1
  - soqt=1.6.0a=h04f5b5a_1000
  - sortedcollections=1.1.1=py_0
  - sortedcontainers=2.1.0=py_0
  - sphinx=1.8.3=py36_1000
  - sphinxcontrib-websupport=1.1.0=py_1
  - sqlite=3.20.1=0
  - suitesparse=4.5.4=blas_openblas_201
  - swig=3.0.12=h0a44026_1003
  - sympy=1.0=py36_0
  - tbb=2019.3=h04f5b5a_1000
  - tblib=1.3.2=py_1
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py36_1000
  - tinyarray=1.2.1=py36h1702cab_1000
  - tk=8.6.9=ha441bb4_1000
  - toolz=0.9.0=py_1
  - tornado=5.1.1=py36h1de35cc_1000
  - tqdm=4.29.1=py_0
  - traitlets=4.3.2=py36_1000
  - typed-ast=1.2.0=py36h1de35cc_1000
  - urllib3=1.24.1=py36_1000
  - vtk=8.1.1=py36hdceb404_201
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.32.3=py36_0
  - widgetsnbextension=3.4.2=py36_1000
  - wrapt=1.11.1=py36h1de35cc_0
  - xerces-c=3.2.0=h5d6a6da_2
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zeromq=4.2.5=h0a44026_1006
  - zict=0.1.3=py_0
  - zlib=1.2.11=h1de35cc_1004
